version: '3.4'

services:
  php:
    image: php:7.2-fpm
    volumes:
      - ./:/var/www/html
    restart: on-failure
  nginx:
    image: nginx:alpine
    volumes:
      - ./:/var/www/html
      - ./public/nginx.conf:/etc/nginx/nginx.conf:ro
    ports:
      - 4567:80
    restart: on-failure
